[tool.poetry]
name = "rpg-task-cli"
version = "0.1.0"
description = ""
authors = ["Petr Rudichev <petrrudichev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.0"
rich = "^13.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
